name = "firecracker"
compatibility_date = "2024-04-03"
main = "src/index.ts"

compatibility_flags = ["nodejs_compat"]
workers_dev = true

# Browser Rendering API binding
browser = { binding = "BROWSER" }

# [[migrations]]
# tag = "v1"
# new_classes = ["Browser"]

# # Bind an R2 Bucket
# [[r2_buckets]]
# binding = "BUCKET"
# bucket_name = "fire"
# preview_bucket_name = "fire-test"

# # Binding to a Durable Object
# [[durable_objects.bindings]]
# name = "BROWSER"
# class_name = "Browser"

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"                                       # i.e. available in your Worker on env.DB
database_name = "fire"
database_id = "3a056337-d5fc-4e80-ab4f-6ea00b436336"
migrations_dir = "drizzle/migrations"
